### ISSUE TITLE
Fully erroneous on Q2A 1.8

### ISSUE THREAD

**Issue by identify83** [JackSiro/Q2A-Blog-Post-Plugin#7]
I've tested the plugin many times, but it doesn't work as expected. Two offers for the next version:

- make the premium plugin free for all and earn from optional ads
- make it compatible and fully working on new versions of Q2A

**Comment by JackSiro** [comment]
It works with Q2A versions as from 1.6 upwards and wont be free. I dont like ads

**Comment by JackSiro** [comment]
be generous and tell the errors you have experienced and I shall give you the premium one

**Comment by identify83** [comment]
Look dude I just offered you to make it free for enriching its core by helps, it's up to you. I don't like ads too, but we live in the world of ads.

By the way these are my problems with your plugin:

- The plugin makes 3 new fields in DB with some null data, error occurs for Q2A.
- Not compatible with RTL languages and not translatable.
- The categories menu doesn't work at all, reach a conflict with script.
- Commenting is not defined for posts, also recaptcha is not.
- Total and author feed is not defined, also posts are not shown in sitemap.
- Users access is not well shaped to make a tough security.

Lastly, The plugin is supposed to be a good and lite option instead of extra WP beside Q2A.

Regards

**Comment by identify83** [comment]
What is "the old version of new plugin"?
These are what I have:
Plugin version 4.0 not premium
Q2A version 1.8

**Comment by JackSiro** [comment]
Okay I looks like you have the latest version but it's in free version.
I find it is not true for you to say that the plugin is not compatible with q2a 1.8 coz I have users who have given a positive feedback and some even paid the $30 for the premium version. 
Well things like commenting and user permissions can be enjoyed in the premium version. Translation is not my concern at all. Follow the guideline on docs.question2answer.org to translate a plugin.
You might as well as check a plugin by user Ami so you can buy his plugin of $60 which has not free plugin at all.
