### ISSUE TITLE
error on blog post page

### ISSUE THREAD

**Issue by zerg052689** [Jacksiro/Q2A-Blog-Post-Plugin#8]
Notice: Undefined index: url in /home/r53825azor/public_html/test.9yolo.com/qa-theme/SnowFlat/qa-theme.php on line 370

Notice: Undefined index: title in /home/r53825azor/public_html/test.9yolo.com/qa-theme/SnowFlat/qa-theme.php on line 370

**Comment by JackSiro** [comment]
buy this plugin and get an error free plugin is all i can see. Free plugin is not maintained as the premium one
